// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cappcraft.proto

package org.cappmc.SNIPER722.capplogin.object;

public final class CappcraftOuterClass {
  private CappcraftOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lu_McBox_Protos_ValidateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lu_McBox_Protos_ValidateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lu_McBox_Protos_ValidateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lu_McBox_Protos_ValidateUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017Cappcraft.proto\022\017Lu.McBox.Protos\"5\n\023Va" +
      "lidateUserRequest\022\020\n\010Username\030\001 \001(\t\022\014\n\004U" +
      "UID\030\002 \001(\t\"5\n\024ValidateUserResponse\022\014\n\004Cod" +
      "e\030\001 \001(\005\022\017\n\007Message\030\002 \001(\t2j\n\tCappcraft\022]\n" +
      "\014ValidateUser\022$.Lu.McBox.Protos.Validate" +
      "UserRequest\032%.Lu.McBox.Protos.ValidateUs" +
      "erResponse\"\000B)\n%org.cappmc.SNIPER722.cap" +
      "plogin.objectP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Lu_McBox_Protos_ValidateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Lu_McBox_Protos_ValidateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lu_McBox_Protos_ValidateUserRequest_descriptor,
        new String[] { "Username", "UUID", });
    internal_static_Lu_McBox_Protos_ValidateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Lu_McBox_Protos_ValidateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lu_McBox_Protos_ValidateUserResponse_descriptor,
        new String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
