// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cappcraft.proto

package org.cappmc.SNIPER722.capplogin.object;

public interface ValidateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lu.McBox.Protos.ValidateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string Username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string UUID = 2;</code>
   */
  String getUUID();
  /**
   * <code>string UUID = 2;</code>
   */
  com.google.protobuf.ByteString
      getUUIDBytes();
}
