// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cappcraft.proto

package org.cappmc.SNIPER722.capplogin.object;

public interface ValidateUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lu.McBox.Protos.ValidateUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0 = false, 1 = OK , -1 = Exception
   * </pre>
   *
   * <code>int32 Code = 1;</code>
   */
  int getCode();

  /**
   * <code>string Message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string Message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
